### ISSUE TITLE
NAS USB_COPY_BUTTON

### ISSUE THREAD

**Issue by artvel** [mafredri/asustor_as-6xxt#2]
Hey @mafredri 

any clue how to receive events of the `USB_COPY_BUTTON`?

Cheers

**Comment by mafredri** [comment]
Whoops, missed that you had opened a new issue here.

Hmm, I do believe I had it figured out at one point, but I can't really remember anymore. It was either via the GPIOs on the IT87 chip or via ACPI button (most likely GPIOs). It may also differ based on model. At least the button press monitoring was handled by `emboardmand` on ADM, so that's one place you could start looking, if you're interested in figuring it out.

**Comment by mafredri** [comment]
@artvel you might want to check out my latest project: https://github.com/mafredri/asustor-platform-driver

It has USB copy button support. ☺️
